name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - release-3.0-multiarch

env:
  IMAGE_NAME: ks-installer
  IMAGE_REPO: lisy09kubesphere
  IMAGE_VERSION: v3.0.0
  DOCKER_PLATFORMS: linux/amd64,linux/arm64

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push image
        run: |
          IMAGE_ID=$IMAGE_REPO/$IMAGE_NAME
          echo IMAGE_ID=$IMAGE_ID

          docker buildx build \
            --file Dockerfile
            --tag $IMAGE_ID:$IMAGE_VERSION \
            --platform $DOCKER_PLATFORMS .

          docker push $IMAGE_ID:$IMAGE_VERSION
